### ISSUE TITLE
EM fails with Exasol version 8.x

### ISSUE THREAD

**Issue by kaklakariada** [exasol/extension-manager#107]
When running EM with an Exasol 8.x database, requests fail with the following log message:

```
2023/06/30 09:39:36 ERROR Internal server error -> failed to read metadata tables. Cause: failed to read SYS.EXA_ALL_VIRTUAL_SCHEMAS: E-EGOD-11: execution failed with SQL error code '42000' and message 'object ADAPTER_SCRIPT not found [line 2, column 35] (Session: 1770119993011011584)'
```

**Comment by ckunki** [comment]
Currently using `prerelease-8.17.0` still fails with "VM crashed" anyway.
So regardless of this ticket currently there is no version 8 and higher that can successfully be used with EM.
