### ISSUE TITLE
Use matching extension manager version in integration tests

### ISSUE THREAD

**Issue by kaklakariada** [exasol/extension-manager#77]
Currently integration tests always use the latest extension manager version. This is a problem for these reasons:
* This will break existing tests for extensions when a new, incompatible version of the extension manager is published.
* You want to test an extension against a specific previous release of extension manager.

Instead of using version `latest` the tests should use the EM version they where built against. We can implement this by using the current project version as default instead of `latest` in method [ExtensionTestConfig.getExtensionManagerVersion()](https://github.com/exasol/extension-manager/blob/0ba7b75a79dc3a64eadef45c22a1f36eea006008/extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/ExtensionTestConfig.java#L71-L79).

- [x] Verify consistent versions in `.project-keeper.yml` and `pom.xml` (`properties/revision`)
- [x] Use current version for installing EM

**Comment by kaklakariada** [comment]
We can implement this by using another default value in method [ExtensionTestConfig.getExtensionManagerVersion()](https://github.com/exasol/extension-manager/blob/0ba7b75a79dc3a64eadef45c22a1f36eea006008/extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/ExtensionTestConfig.java#L71-L79) instead of `latest`.

**Comment by ckunki** [comment]
Some findings.
